[tool.black]
line-length = 119
target-version = ["py38"]

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = [
    "api",
    "config",
    "enums",
    "event_handlers",
    "schemas"
]

line_length = 119
lines_after_imports = 2
multi_line_output = 3
use_parentheses = true